# This would be my comments
---
spring:
  application:
    name: sb-aslan-kafka-template
  profiles:
    active:
      - local
management:
  cloudfoundary:
    skip-ssl-validation: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/"
  endpoint:
    beans:
      enabled: true
# session timeout: Default value is 30 minutes
server:
  servlet:
    session:
      persistent: true
      timeout: 15m